name: FoF Discussion Language PHP

on: [workflow_dispatch, push, pull_request]

jobs:
  run:
    uses: flarum/framework/.github/workflows/REUSABLE_backend.yml@1.x
    with:
      enable_backend_testing: true
      enable_phpstan: true
      php_ini_values: E_ALL & ~E_DEPRECATED & ~E_USER_DEPRECATED

      backend_directory: .
